global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sre-lab'

scrape_configs:
  # Monitoramento básico
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Métricas do Grafana
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
    scheme: http
    tls_config:
      insecure_skip_verify: true

  # Docker Engine Metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']